# Generated by Django 4.2.11 on 2024-12-07 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('percent', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='shop.category')),
                ('product', models.ManyToManyField(blank=True, null=True, to='shop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
