# Generated by Django 4.2.11 on 2024-12-18 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [("shop", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SpecialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "special_price_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percent", "Percent")],
                        default="fixed",
                        max_length=7,
                    ),
                ),
                ("special_price_value", models.PositiveIntegerField()),
                ("categories", models.ManyToManyField(blank=True, to="shop.category")),
                ("products", models.ManyToManyField(blank=True, to="shop.product")),
            ],
            options={"abstract": False},
        )
    ]
