# Generated by Django 4.2.11 on 2024-12-27 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("discount", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_code_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percent", "Percent")],
                        default="fixed",
                        max_length=7,
                    ),
                ),
                ("discount_code_value", models.PositiveIntegerField()),
            ],
            options={"abstract": False},
        )
    ]
