# Generated by Django 4.2.11 on 2024-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountprice',
            name='fixed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
