# Generated by Django 4.2.11 on 2024-12-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("discount", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="specialprice", name="fixed"),
        migrations.RemoveField(model_name="specialprice", name="percent"),
        migrations.AddField(
            model_name="specialprice",
            name="special_value",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
