# Generated by Django 4.2.11 on 2024-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        ("discount", "0002_alter_discountprice_fixed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountprice",
            name="category",
            field=models.ManyToManyField(blank=True, to="shop.category"),
        ),
        migrations.AlterField(
            model_name="discountprice",
            name="product",
            field=models.ManyToManyField(blank=True, to="shop.product"),
        ),
    ]
