# Generated by Django 4.2.11 on 2024-12-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("discount", "0002_remove_specialprice_fixed_and_more")]

    operations = [
        migrations.RenameField(
            model_name="specialprice", old_name="special_value", new_name="value"
        )
    ]
