# Generated by Django 4.2.11 on 2024-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("discount", "0003_alter_discountprice_category_and_more")]

    operations = [
        migrations.RenameField(
            model_name="discountprice", old_name="category", new_name="categories"
        ),
        migrations.RenameField(
            model_name="discountprice", old_name="product", new_name="products"
        ),
    ]
