# Generated by Django 4.2.11 on 2024-12-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("failed", "failed"),
                    ("canceled", "canceled"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                ],
                default="pending_payment",
                max_length=15,
            ),
        )
    ]
