# Generated by Django 4.2.11 on 2025-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0002_alter_order_status")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order", name="discount_id", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.IntegerField(default=0),
        ),
    ]
