# Generated by Django 4.2.11 on 2024-12-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0002_alter_order_status")]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(default="", max_length=100),
        )
    ]
