# Generated by Django 4.2.11 on 2025-01-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("checkout", "0003_cart_session_key")]

    operations = [migrations.RemoveField(model_name="cart", name="session_key")]
