# Generated by Django 4.2.11 on 2025-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0004_remove_cart_session_key")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order", name="discount_id", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.IntegerField(default=0),
        ),
    ]
