# Generated by Django 4.2.11 on 2024-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_total_price_alter_orderproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarinpal_authority',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
