# Generated by Django 4.2.11 on 2024-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_zarinpal_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.IntegerField(null=True),
        ),
    ]
